// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/file/server.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_api_file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0}
}

func (x *Server) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *Server) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Server_GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GetRequest) Reset() {
	*x = Server_GetRequest{}
	mi := &file_api_file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GetRequest) ProtoMessage() {}

func (x *Server_GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GetRequest.ProtoReflect.Descriptor instead.
func (*Server_GetRequest) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Server_GetRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Server_GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Server                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GetResponse) Reset() {
	*x = Server_GetResponse{}
	mi := &file_api_file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GetResponse) ProtoMessage() {}

func (x *Server_GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GetResponse.ProtoReflect.Descriptor instead.
func (*Server_GetResponse) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Server_GetResponse) GetResult() *Server {
	if x != nil {
		return x.Result
	}
	return nil
}

type Server_StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Option        string                 `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_StartRequest) Reset() {
	*x = Server_StartRequest{}
	mi := &file_api_file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_StartRequest) ProtoMessage() {}

func (x *Server_StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_StartRequest.ProtoReflect.Descriptor instead.
func (*Server_StartRequest) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Server_StartRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Server_StartRequest) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

type Server_StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Server                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_StartResponse) Reset() {
	*x = Server_StartResponse{}
	mi := &file_api_file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_StartResponse) ProtoMessage() {}

func (x *Server_StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_StartResponse.ProtoReflect.Descriptor instead.
func (*Server_StartResponse) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Server_StartResponse) GetResult() *Server {
	if x != nil {
		return x.Result
	}
	return nil
}

type Server_StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_StopRequest) Reset() {
	*x = Server_StopRequest{}
	mi := &file_api_file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_StopRequest) ProtoMessage() {}

func (x *Server_StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_StopRequest.ProtoReflect.Descriptor instead.
func (*Server_StopRequest) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Server_StopRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Server_StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_StopResponse) Reset() {
	*x = Server_StopResponse{}
	mi := &file_api_file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_StopResponse) ProtoMessage() {}

func (x *Server_StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_StopResponse.ProtoReflect.Descriptor instead.
func (*Server_StopResponse) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 5}
}

var File_api_file_server_proto protoreflect.FileDescriptor

const file_api_file_server_proto_rawDesc = "" +
	"\n" +
	"\x15api/file/server.proto\x12\bapi.file\"\xd1\x02\n" +
	"\x06Server\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x1a7\n" +
	"\vGetResponse\x12(\n" +
	"\x06result\x18\x01 \x01(\v2\x10.api.file.ServerR\x06result\x1a:\n" +
	"\fStartRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06option\x18\x02 \x01(\tR\x06option\x1a9\n" +
	"\rStartResponse\x12(\n" +
	"\x06result\x18\x01 \x01(\v2\x10.api.file.ServerR\x06result\x1a!\n" +
	"\vStopRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x1a\x0e\n" +
	"\fStopResponse2\xf9\x01\n" +
	"\rServerService\x12N\n" +
	"\vStartServer\x12\x1d.api.file.Server.StartRequest\x1a\x1e.api.file.Server.StartResponse\"\x00\x12K\n" +
	"\n" +
	"StopServer\x12\x1c.api.file.Server.StopRequest\x1a\x1d.api.file.Server.StopResponse\"\x00\x12K\n" +
	"\fServerStatus\x12\x1b.api.file.Server.GetRequest\x1a\x1c.api.file.Server.GetResponse\"\x00B\x9b\x01\n" +
	"\fcom.api.fileB\vServerProtoP\x01Z=github.com/honmaple/maple-file/server/internal/proto/api/file\xa2\x02\x03AFX\xaa\x02\bApi.File\xca\x02\bApi\\File\xe2\x02\x14Api\\File\\GPBMetadata\xea\x02\tApi::Fileb\x06proto3"

var (
	file_api_file_server_proto_rawDescOnce sync.Once
	file_api_file_server_proto_rawDescData []byte
)

func file_api_file_server_proto_rawDescGZIP() []byte {
	file_api_file_server_proto_rawDescOnce.Do(func() {
		file_api_file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_file_server_proto_rawDesc), len(file_api_file_server_proto_rawDesc)))
	})
	return file_api_file_server_proto_rawDescData
}

var file_api_file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_file_server_proto_goTypes = []any{
	(*Server)(nil),               // 0: api.file.Server
	(*Server_GetRequest)(nil),    // 1: api.file.Server.GetRequest
	(*Server_GetResponse)(nil),   // 2: api.file.Server.GetResponse
	(*Server_StartRequest)(nil),  // 3: api.file.Server.StartRequest
	(*Server_StartResponse)(nil), // 4: api.file.Server.StartResponse
	(*Server_StopRequest)(nil),   // 5: api.file.Server.StopRequest
	(*Server_StopResponse)(nil),  // 6: api.file.Server.StopResponse
}
var file_api_file_server_proto_depIdxs = []int32{
	0, // 0: api.file.Server.GetResponse.result:type_name -> api.file.Server
	0, // 1: api.file.Server.StartResponse.result:type_name -> api.file.Server
	3, // 2: api.file.ServerService.StartServer:input_type -> api.file.Server.StartRequest
	5, // 3: api.file.ServerService.StopServer:input_type -> api.file.Server.StopRequest
	1, // 4: api.file.ServerService.ServerStatus:input_type -> api.file.Server.GetRequest
	4, // 5: api.file.ServerService.StartServer:output_type -> api.file.Server.StartResponse
	6, // 6: api.file.ServerService.StopServer:output_type -> api.file.Server.StopResponse
	2, // 7: api.file.ServerService.ServerStatus:output_type -> api.file.Server.GetResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_file_server_proto_init() }
func file_api_file_server_proto_init() {
	if File_api_file_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_file_server_proto_rawDesc), len(file_api_file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_file_server_proto_goTypes,
		DependencyIndexes: file_api_file_server_proto_depIdxs,
		MessageInfos:      file_api_file_server_proto_msgTypes,
	}.Build()
	File_api_file_server_proto = out.File
	file_api_file_server_proto_goTypes = nil
	file_api_file_server_proto_depIdxs = nil
}
