// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/file/server.proto

package file

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExternalServerService_StartServer_FullMethodName  = "/api.file.ExternalServerService/StartServer"
	ExternalServerService_StopServer_FullMethodName   = "/api.file.ExternalServerService/StopServer"
	ExternalServerService_ServerStatus_FullMethodName = "/api.file.ExternalServerService/ServerStatus"
)

// ExternalServerServiceClient is the client API for ExternalServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExternalServerServiceClient interface {
	StartServer(ctx context.Context, in *ExternalServer_StartRequest, opts ...grpc.CallOption) (*ExternalServer_StartResponse, error)
	StopServer(ctx context.Context, in *ExternalServer_StopRequest, opts ...grpc.CallOption) (*ExternalServer_StopResponse, error)
	ServerStatus(ctx context.Context, in *ExternalServer_GetRequest, opts ...grpc.CallOption) (*ExternalServer_GetResponse, error)
}

type externalServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalServerServiceClient(cc grpc.ClientConnInterface) ExternalServerServiceClient {
	return &externalServerServiceClient{cc}
}

func (c *externalServerServiceClient) StartServer(ctx context.Context, in *ExternalServer_StartRequest, opts ...grpc.CallOption) (*ExternalServer_StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalServer_StartResponse)
	err := c.cc.Invoke(ctx, ExternalServerService_StartServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalServerServiceClient) StopServer(ctx context.Context, in *ExternalServer_StopRequest, opts ...grpc.CallOption) (*ExternalServer_StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalServer_StopResponse)
	err := c.cc.Invoke(ctx, ExternalServerService_StopServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalServerServiceClient) ServerStatus(ctx context.Context, in *ExternalServer_GetRequest, opts ...grpc.CallOption) (*ExternalServer_GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalServer_GetResponse)
	err := c.cc.Invoke(ctx, ExternalServerService_ServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalServerServiceServer is the server API for ExternalServerService service.
// All implementations must embed UnimplementedExternalServerServiceServer
// for forward compatibility.
type ExternalServerServiceServer interface {
	StartServer(context.Context, *ExternalServer_StartRequest) (*ExternalServer_StartResponse, error)
	StopServer(context.Context, *ExternalServer_StopRequest) (*ExternalServer_StopResponse, error)
	ServerStatus(context.Context, *ExternalServer_GetRequest) (*ExternalServer_GetResponse, error)
	mustEmbedUnimplementedExternalServerServiceServer()
}

// UnimplementedExternalServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExternalServerServiceServer struct{}

func (UnimplementedExternalServerServiceServer) StartServer(context.Context, *ExternalServer_StartRequest) (*ExternalServer_StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartServer not implemented")
}
func (UnimplementedExternalServerServiceServer) StopServer(context.Context, *ExternalServer_StopRequest) (*ExternalServer_StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopServer not implemented")
}
func (UnimplementedExternalServerServiceServer) ServerStatus(context.Context, *ExternalServer_GetRequest) (*ExternalServer_GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerStatus not implemented")
}
func (UnimplementedExternalServerServiceServer) mustEmbedUnimplementedExternalServerServiceServer() {}
func (UnimplementedExternalServerServiceServer) testEmbeddedByValue()                               {}

// UnsafeExternalServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalServerServiceServer will
// result in compilation errors.
type UnsafeExternalServerServiceServer interface {
	mustEmbedUnimplementedExternalServerServiceServer()
}

func RegisterExternalServerServiceServer(s grpc.ServiceRegistrar, srv ExternalServerServiceServer) {
	// If the following call pancis, it indicates UnimplementedExternalServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExternalServerService_ServiceDesc, srv)
}

func _ExternalServerService_StartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalServer_StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServerServiceServer).StartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalServerService_StartServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServerServiceServer).StartServer(ctx, req.(*ExternalServer_StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalServerService_StopServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalServer_StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServerServiceServer).StopServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalServerService_StopServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServerServiceServer).StopServer(ctx, req.(*ExternalServer_StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalServerService_ServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalServer_GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServerServiceServer).ServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalServerService_ServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServerServiceServer).ServerStatus(ctx, req.(*ExternalServer_GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExternalServerService_ServiceDesc is the grpc.ServiceDesc for ExternalServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.file.ExternalServerService",
	HandlerType: (*ExternalServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartServer",
			Handler:    _ExternalServerService_StartServer_Handler,
		},
		{
			MethodName: "StopServer",
			Handler:    _ExternalServerService_StopServer_Handler,
		},
		{
			MethodName: "ServerStatus",
			Handler:    _ExternalServerService_ServerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/file/server.proto",
}
