// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/file/server.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExternalServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalServer) Reset() {
	*x = ExternalServer{}
	mi := &file_api_file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalServer) ProtoMessage() {}

func (x *ExternalServer) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalServer.ProtoReflect.Descriptor instead.
func (*ExternalServer) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalServer) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ExternalServer) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ExternalServer) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExternalServer_GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalServer_GetRequest) Reset() {
	*x = ExternalServer_GetRequest{}
	mi := &file_api_file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalServer_GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalServer_GetRequest) ProtoMessage() {}

func (x *ExternalServer_GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalServer_GetRequest.ProtoReflect.Descriptor instead.
func (*ExternalServer_GetRequest) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ExternalServer_GetRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ExternalServer_GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ExternalServer        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalServer_GetResponse) Reset() {
	*x = ExternalServer_GetResponse{}
	mi := &file_api_file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalServer_GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalServer_GetResponse) ProtoMessage() {}

func (x *ExternalServer_GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalServer_GetResponse.ProtoReflect.Descriptor instead.
func (*ExternalServer_GetResponse) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ExternalServer_GetResponse) GetResult() *ExternalServer {
	if x != nil {
		return x.Result
	}
	return nil
}

type ExternalServer_StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Option        string                 `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalServer_StartRequest) Reset() {
	*x = ExternalServer_StartRequest{}
	mi := &file_api_file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalServer_StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalServer_StartRequest) ProtoMessage() {}

func (x *ExternalServer_StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalServer_StartRequest.ProtoReflect.Descriptor instead.
func (*ExternalServer_StartRequest) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ExternalServer_StartRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExternalServer_StartRequest) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

type ExternalServer_StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ExternalServer        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalServer_StartResponse) Reset() {
	*x = ExternalServer_StartResponse{}
	mi := &file_api_file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalServer_StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalServer_StartResponse) ProtoMessage() {}

func (x *ExternalServer_StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalServer_StartResponse.ProtoReflect.Descriptor instead.
func (*ExternalServer_StartResponse) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ExternalServer_StartResponse) GetResult() *ExternalServer {
	if x != nil {
		return x.Result
	}
	return nil
}

type ExternalServer_StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalServer_StopRequest) Reset() {
	*x = ExternalServer_StopRequest{}
	mi := &file_api_file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalServer_StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalServer_StopRequest) ProtoMessage() {}

func (x *ExternalServer_StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalServer_StopRequest.ProtoReflect.Descriptor instead.
func (*ExternalServer_StopRequest) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ExternalServer_StopRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ExternalServer_StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalServer_StopResponse) Reset() {
	*x = ExternalServer_StopResponse{}
	mi := &file_api_file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalServer_StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalServer_StopResponse) ProtoMessage() {}

func (x *ExternalServer_StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalServer_StopResponse.ProtoReflect.Descriptor instead.
func (*ExternalServer_StopResponse) Descriptor() ([]byte, []int) {
	return file_api_file_server_proto_rawDescGZIP(), []int{0, 5}
}

var File_api_file_server_proto protoreflect.FileDescriptor

const file_api_file_server_proto_rawDesc = "" +
	"\n" +
	"\x15api/file/server.proto\x12\bapi.file\"\xe9\x02\n" +
	"\x0eExternalServer\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x1a?\n" +
	"\vGetResponse\x120\n" +
	"\x06result\x18\x01 \x01(\v2\x18.api.file.ExternalServerR\x06result\x1a:\n" +
	"\fStartRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06option\x18\x02 \x01(\tR\x06option\x1aA\n" +
	"\rStartResponse\x120\n" +
	"\x06result\x18\x01 \x01(\v2\x18.api.file.ExternalServerR\x06result\x1a!\n" +
	"\vStopRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x1a\x0e\n" +
	"\fStopResponse2\xb1\x02\n" +
	"\x15ExternalServerService\x12^\n" +
	"\vStartServer\x12%.api.file.ExternalServer.StartRequest\x1a&.api.file.ExternalServer.StartResponse\"\x00\x12[\n" +
	"\n" +
	"StopServer\x12$.api.file.ExternalServer.StopRequest\x1a%.api.file.ExternalServer.StopResponse\"\x00\x12[\n" +
	"\fServerStatus\x12#.api.file.ExternalServer.GetRequest\x1a$.api.file.ExternalServer.GetResponse\"\x00B\x9b\x01\n" +
	"\fcom.api.fileB\vServerProtoP\x01Z=github.com/honmaple/maple-file/server/internal/proto/api/file\xa2\x02\x03AFX\xaa\x02\bApi.File\xca\x02\bApi\\File\xe2\x02\x14Api\\File\\GPBMetadata\xea\x02\tApi::Fileb\x06proto3"

var (
	file_api_file_server_proto_rawDescOnce sync.Once
	file_api_file_server_proto_rawDescData []byte
)

func file_api_file_server_proto_rawDescGZIP() []byte {
	file_api_file_server_proto_rawDescOnce.Do(func() {
		file_api_file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_file_server_proto_rawDesc), len(file_api_file_server_proto_rawDesc)))
	})
	return file_api_file_server_proto_rawDescData
}

var file_api_file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_file_server_proto_goTypes = []any{
	(*ExternalServer)(nil),               // 0: api.file.ExternalServer
	(*ExternalServer_GetRequest)(nil),    // 1: api.file.ExternalServer.GetRequest
	(*ExternalServer_GetResponse)(nil),   // 2: api.file.ExternalServer.GetResponse
	(*ExternalServer_StartRequest)(nil),  // 3: api.file.ExternalServer.StartRequest
	(*ExternalServer_StartResponse)(nil), // 4: api.file.ExternalServer.StartResponse
	(*ExternalServer_StopRequest)(nil),   // 5: api.file.ExternalServer.StopRequest
	(*ExternalServer_StopResponse)(nil),  // 6: api.file.ExternalServer.StopResponse
}
var file_api_file_server_proto_depIdxs = []int32{
	0, // 0: api.file.ExternalServer.GetResponse.result:type_name -> api.file.ExternalServer
	0, // 1: api.file.ExternalServer.StartResponse.result:type_name -> api.file.ExternalServer
	3, // 2: api.file.ExternalServerService.StartServer:input_type -> api.file.ExternalServer.StartRequest
	5, // 3: api.file.ExternalServerService.StopServer:input_type -> api.file.ExternalServer.StopRequest
	1, // 4: api.file.ExternalServerService.ServerStatus:input_type -> api.file.ExternalServer.GetRequest
	4, // 5: api.file.ExternalServerService.StartServer:output_type -> api.file.ExternalServer.StartResponse
	6, // 6: api.file.ExternalServerService.StopServer:output_type -> api.file.ExternalServer.StopResponse
	2, // 7: api.file.ExternalServerService.ServerStatus:output_type -> api.file.ExternalServer.GetResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_file_server_proto_init() }
func file_api_file_server_proto_init() {
	if File_api_file_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_file_server_proto_rawDesc), len(file_api_file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_file_server_proto_goTypes,
		DependencyIndexes: file_api_file_server_proto_depIdxs,
		MessageInfos:      file_api_file_server_proto_msgTypes,
	}.Build()
	File_api_file_server_proto = out.File
	file_api_file_server_proto_goTypes = nil
	file_api_file_server_proto_depIdxs = nil
}
