// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/task/persist.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersistTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: gorm:"primary_key;auto_increment"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key;auto_increment"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"not null;unique"
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty" gorm:"not null;unique"`
	Status        bool   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Type          string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Option        string `protobuf:"bytes,7,opt,name=option,proto3" json:"option,omitempty"`
	CronOption    string `protobuf:"bytes,8,opt,name=cron_option,json=cronOption,proto3" json:"cron_option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask) Reset() {
	*x = PersistTask{}
	mi := &file_api_task_persist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask) ProtoMessage() {}

func (x *PersistTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask.ProtoReflect.Descriptor instead.
func (*PersistTask) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{0}
}

func (x *PersistTask) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersistTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PersistTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PersistTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersistTask) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *PersistTask) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PersistTask) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

func (x *PersistTask) GetCronOption() string {
	if x != nil {
		return x.CronOption
	}
	return ""
}

type ListPersistTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        map[string]string      `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersistTasksRequest) Reset() {
	*x = ListPersistTasksRequest{}
	mi := &file_api_task_persist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersistTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersistTasksRequest) ProtoMessage() {}

func (x *ListPersistTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersistTasksRequest.ProtoReflect.Descriptor instead.
func (*ListPersistTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{1}
}

func (x *ListPersistTasksRequest) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListPersistTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PersistTask         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersistTasksResponse) Reset() {
	*x = ListPersistTasksResponse{}
	mi := &file_api_task_persist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersistTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersistTasksResponse) ProtoMessage() {}

func (x *ListPersistTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersistTasksResponse.ProtoReflect.Descriptor instead.
func (*ListPersistTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{2}
}

func (x *ListPersistTasksResponse) GetResults() []*PersistTask {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreatePersistTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *PersistTask           `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersistTaskRequest) Reset() {
	*x = CreatePersistTaskRequest{}
	mi := &file_api_task_persist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersistTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersistTaskRequest) ProtoMessage() {}

func (x *CreatePersistTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersistTaskRequest.ProtoReflect.Descriptor instead.
func (*CreatePersistTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePersistTaskRequest) GetPayload() *PersistTask {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreatePersistTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *PersistTask           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersistTaskResponse) Reset() {
	*x = CreatePersistTaskResponse{}
	mi := &file_api_task_persist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersistTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersistTaskResponse) ProtoMessage() {}

func (x *CreatePersistTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersistTaskResponse.ProtoReflect.Descriptor instead.
func (*CreatePersistTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePersistTaskResponse) GetResult() *PersistTask {
	if x != nil {
		return x.Result
	}
	return nil
}

type UpdatePersistTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *PersistTask           `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersistTaskRequest) Reset() {
	*x = UpdatePersistTaskRequest{}
	mi := &file_api_task_persist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersistTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersistTaskRequest) ProtoMessage() {}

func (x *UpdatePersistTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersistTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersistTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePersistTaskRequest) GetPayload() *PersistTask {
	if x != nil {
		return x.Payload
	}
	return nil
}

type UpdatePersistTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *PersistTask           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersistTaskResponse) Reset() {
	*x = UpdatePersistTaskResponse{}
	mi := &file_api_task_persist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersistTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersistTaskResponse) ProtoMessage() {}

func (x *UpdatePersistTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersistTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdatePersistTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePersistTaskResponse) GetResult() *PersistTask {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeletePersistTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersistTaskRequest) Reset() {
	*x = DeletePersistTaskRequest{}
	mi := &file_api_task_persist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersistTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersistTaskRequest) ProtoMessage() {}

func (x *DeletePersistTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersistTaskRequest.ProtoReflect.Descriptor instead.
func (*DeletePersistTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePersistTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePersistTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersistTaskResponse) Reset() {
	*x = DeletePersistTaskResponse{}
	mi := &file_api_task_persist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersistTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersistTaskResponse) ProtoMessage() {}

func (x *DeletePersistTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersistTaskResponse.ProtoReflect.Descriptor instead.
func (*DeletePersistTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{8}
}

type TestPersistTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *PersistTask           `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPersistTaskRequest) Reset() {
	*x = TestPersistTaskRequest{}
	mi := &file_api_task_persist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPersistTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPersistTaskRequest) ProtoMessage() {}

func (x *TestPersistTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPersistTaskRequest.ProtoReflect.Descriptor instead.
func (*TestPersistTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{9}
}

func (x *TestPersistTaskRequest) GetPayload() *PersistTask {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TestPersistTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPersistTaskResponse) Reset() {
	*x = TestPersistTaskResponse{}
	mi := &file_api_task_persist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPersistTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPersistTaskResponse) ProtoMessage() {}

func (x *TestPersistTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPersistTaskResponse.ProtoReflect.Descriptor instead.
func (*TestPersistTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{10}
}

type ExecutePersistTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePersistTaskRequest) Reset() {
	*x = ExecutePersistTaskRequest{}
	mi := &file_api_task_persist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePersistTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePersistTaskRequest) ProtoMessage() {}

func (x *ExecutePersistTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePersistTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecutePersistTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{11}
}

func (x *ExecutePersistTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExecutePersistTaskRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type ExecutePersistTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePersistTaskResponse) Reset() {
	*x = ExecutePersistTaskResponse{}
	mi := &file_api_task_persist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePersistTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePersistTaskResponse) ProtoMessage() {}

func (x *ExecutePersistTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePersistTaskResponse.ProtoReflect.Descriptor instead.
func (*ExecutePersistTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{12}
}

var File_api_task_persist_proto protoreflect.FileDescriptor

const file_api_task_persist_proto_rawDesc = "" +
	"\n" +
	"\x16api/task/persist.proto\x12\bapi.task\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x02\n" +
	"\vPersistTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x16\n" +
	"\x06option\x18\a \x01(\tR\x06option\x12\x1f\n" +
	"\vcron_option\x18\b \x01(\tR\n" +
	"cronOption\"\x9b\x01\n" +
	"\x17ListPersistTasksRequest\x12E\n" +
	"\x06filter\x18\x01 \x03(\v2-.api.task.ListPersistTasksRequest.FilterEntryR\x06filter\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x18ListPersistTasksResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.api.task.PersistTaskR\aresults\"K\n" +
	"\x18CreatePersistTaskRequest\x12/\n" +
	"\apayload\x18\x01 \x01(\v2\x15.api.task.PersistTaskR\apayload\"J\n" +
	"\x19CreatePersistTaskResponse\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.api.task.PersistTaskR\x06result\"K\n" +
	"\x18UpdatePersistTaskRequest\x12/\n" +
	"\apayload\x18\x01 \x01(\v2\x15.api.task.PersistTaskR\apayload\"J\n" +
	"\x19UpdatePersistTaskResponse\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.api.task.PersistTaskR\x06result\"*\n" +
	"\x18DeletePersistTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x1b\n" +
	"\x19DeletePersistTaskResponse\"I\n" +
	"\x16TestPersistTaskRequest\x12/\n" +
	"\apayload\x18\x01 \x01(\v2\x15.api.task.PersistTaskR\apayload\"\x19\n" +
	"\x17TestPersistTaskResponse\"D\n" +
	"\x19ExecutePersistTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\"\x1c\n" +
	"\x1aExecutePersistTaskResponseB\x9c\x01\n" +
	"\fcom.api.taskB\fPersistProtoP\x01Z=github.com/honmaple/maple-file/server/internal/proto/api/task\xa2\x02\x03ATX\xaa\x02\bApi.Task\xca\x02\bApi\\Task\xe2\x02\x14Api\\Task\\GPBMetadata\xea\x02\tApi::Taskb\x06proto3"

var (
	file_api_task_persist_proto_rawDescOnce sync.Once
	file_api_task_persist_proto_rawDescData []byte
)

func file_api_task_persist_proto_rawDescGZIP() []byte {
	file_api_task_persist_proto_rawDescOnce.Do(func() {
		file_api_task_persist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_task_persist_proto_rawDesc), len(file_api_task_persist_proto_rawDesc)))
	})
	return file_api_task_persist_proto_rawDescData
}

var file_api_task_persist_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_task_persist_proto_goTypes = []any{
	(*PersistTask)(nil),                // 0: api.task.PersistTask
	(*ListPersistTasksRequest)(nil),    // 1: api.task.ListPersistTasksRequest
	(*ListPersistTasksResponse)(nil),   // 2: api.task.ListPersistTasksResponse
	(*CreatePersistTaskRequest)(nil),   // 3: api.task.CreatePersistTaskRequest
	(*CreatePersistTaskResponse)(nil),  // 4: api.task.CreatePersistTaskResponse
	(*UpdatePersistTaskRequest)(nil),   // 5: api.task.UpdatePersistTaskRequest
	(*UpdatePersistTaskResponse)(nil),  // 6: api.task.UpdatePersistTaskResponse
	(*DeletePersistTaskRequest)(nil),   // 7: api.task.DeletePersistTaskRequest
	(*DeletePersistTaskResponse)(nil),  // 8: api.task.DeletePersistTaskResponse
	(*TestPersistTaskRequest)(nil),     // 9: api.task.TestPersistTaskRequest
	(*TestPersistTaskResponse)(nil),    // 10: api.task.TestPersistTaskResponse
	(*ExecutePersistTaskRequest)(nil),  // 11: api.task.ExecutePersistTaskRequest
	(*ExecutePersistTaskResponse)(nil), // 12: api.task.ExecutePersistTaskResponse
	nil,                                // 13: api.task.ListPersistTasksRequest.FilterEntry
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
}
var file_api_task_persist_proto_depIdxs = []int32{
	14, // 0: api.task.PersistTask.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: api.task.PersistTask.updated_at:type_name -> google.protobuf.Timestamp
	13, // 2: api.task.ListPersistTasksRequest.filter:type_name -> api.task.ListPersistTasksRequest.FilterEntry
	0,  // 3: api.task.ListPersistTasksResponse.results:type_name -> api.task.PersistTask
	0,  // 4: api.task.CreatePersistTaskRequest.payload:type_name -> api.task.PersistTask
	0,  // 5: api.task.CreatePersistTaskResponse.result:type_name -> api.task.PersistTask
	0,  // 6: api.task.UpdatePersistTaskRequest.payload:type_name -> api.task.PersistTask
	0,  // 7: api.task.UpdatePersistTaskResponse.result:type_name -> api.task.PersistTask
	0,  // 8: api.task.TestPersistTaskRequest.payload:type_name -> api.task.PersistTask
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_task_persist_proto_init() }
func file_api_task_persist_proto_init() {
	if File_api_task_persist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_task_persist_proto_rawDesc), len(file_api_task_persist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_task_persist_proto_goTypes,
		DependencyIndexes: file_api_task_persist_proto_depIdxs,
		MessageInfos:      file_api_task_persist_proto_msgTypes,
	}.Build()
	File_api_task_persist_proto = out.File
	file_api_task_persist_proto_goTypes = nil
	file_api_task_persist_proto_depIdxs = nil
}
