// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: api/task/persist.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersistTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: gorm:"primary_key;auto_increment"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key;auto_increment"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"not null;unique"
	Name       string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty" gorm:"not null;unique"`
	Status     bool   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Type       string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Option     string `protobuf:"bytes,7,opt,name=option,proto3" json:"option,omitempty"`
	CronOption string `protobuf:"bytes,8,opt,name=cron_option,json=cronOption,proto3" json:"cron_option,omitempty"`
}

func (x *PersistTask) Reset() {
	*x = PersistTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersistTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask) ProtoMessage() {}

func (x *PersistTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask.ProtoReflect.Descriptor instead.
func (*PersistTask) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{0}
}

func (x *PersistTask) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersistTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PersistTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PersistTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersistTask) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *PersistTask) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PersistTask) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

func (x *PersistTask) GetCronOption() string {
	if x != nil {
		return x.CronOption
	}
	return ""
}

type ListPersistTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter map[string]string `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ListPersistTasksRequest) Reset() {
	*x = ListPersistTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPersistTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersistTasksRequest) ProtoMessage() {}

func (x *ListPersistTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersistTasksRequest.ProtoReflect.Descriptor instead.
func (*ListPersistTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{1}
}

func (x *ListPersistTasksRequest) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListPersistTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*PersistTask `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ListPersistTasksResponse) Reset() {
	*x = ListPersistTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPersistTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersistTasksResponse) ProtoMessage() {}

func (x *ListPersistTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersistTasksResponse.ProtoReflect.Descriptor instead.
func (*ListPersistTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{2}
}

func (x *ListPersistTasksResponse) GetResults() []*PersistTask {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreatePersistTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *PersistTask `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CreatePersistTaskRequest) Reset() {
	*x = CreatePersistTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePersistTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersistTaskRequest) ProtoMessage() {}

func (x *CreatePersistTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersistTaskRequest.ProtoReflect.Descriptor instead.
func (*CreatePersistTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePersistTaskRequest) GetPayload() *PersistTask {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreatePersistTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *PersistTask `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreatePersistTaskResponse) Reset() {
	*x = CreatePersistTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePersistTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersistTaskResponse) ProtoMessage() {}

func (x *CreatePersistTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersistTaskResponse.ProtoReflect.Descriptor instead.
func (*CreatePersistTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePersistTaskResponse) GetResult() *PersistTask {
	if x != nil {
		return x.Result
	}
	return nil
}

type UpdatePersistTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *PersistTask `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *UpdatePersistTaskRequest) Reset() {
	*x = UpdatePersistTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePersistTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersistTaskRequest) ProtoMessage() {}

func (x *UpdatePersistTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersistTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersistTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePersistTaskRequest) GetPayload() *PersistTask {
	if x != nil {
		return x.Payload
	}
	return nil
}

type UpdatePersistTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *PersistTask `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UpdatePersistTaskResponse) Reset() {
	*x = UpdatePersistTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePersistTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersistTaskResponse) ProtoMessage() {}

func (x *UpdatePersistTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersistTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdatePersistTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePersistTaskResponse) GetResult() *PersistTask {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeletePersistTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePersistTaskRequest) Reset() {
	*x = DeletePersistTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePersistTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersistTaskRequest) ProtoMessage() {}

func (x *DeletePersistTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersistTaskRequest.ProtoReflect.Descriptor instead.
func (*DeletePersistTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePersistTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePersistTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePersistTaskResponse) Reset() {
	*x = DeletePersistTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePersistTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersistTaskResponse) ProtoMessage() {}

func (x *DeletePersistTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersistTaskResponse.ProtoReflect.Descriptor instead.
func (*DeletePersistTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{8}
}

type TestPersistTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *PersistTask `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *TestPersistTaskRequest) Reset() {
	*x = TestPersistTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestPersistTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPersistTaskRequest) ProtoMessage() {}

func (x *TestPersistTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPersistTaskRequest.ProtoReflect.Descriptor instead.
func (*TestPersistTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{9}
}

func (x *TestPersistTaskRequest) GetPayload() *PersistTask {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TestPersistTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestPersistTaskResponse) Reset() {
	*x = TestPersistTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestPersistTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPersistTaskResponse) ProtoMessage() {}

func (x *TestPersistTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPersistTaskResponse.ProtoReflect.Descriptor instead.
func (*TestPersistTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{10}
}

type ExecutePersistTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DryRun bool  `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
}

func (x *ExecutePersistTaskRequest) Reset() {
	*x = ExecutePersistTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutePersistTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePersistTaskRequest) ProtoMessage() {}

func (x *ExecutePersistTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePersistTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecutePersistTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{11}
}

func (x *ExecutePersistTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExecutePersistTaskRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type ExecutePersistTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExecutePersistTaskResponse) Reset() {
	*x = ExecutePersistTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_task_persist_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutePersistTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePersistTaskResponse) ProtoMessage() {}

func (x *ExecutePersistTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_persist_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePersistTaskResponse.ProtoReflect.Descriptor instead.
func (*ExecutePersistTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_persist_proto_rawDescGZIP(), []int{12}
}

var File_api_task_persist_proto protoreflect.FileDescriptor

var file_api_task_persist_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x69,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x61,
	0x73, 0x6b, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x02, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x6f, 0x6e, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x9b, 0x01, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x72, 0x73, 0x69,
	0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45,
	0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65,
	0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x39, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x4b, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x4b, 0x0a,
	0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4a, 0x0a, 0x19, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x61,
	0x73, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4b, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x50,
	0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x4a, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72,
	0x73, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73,
	0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x49, 0x0a, 0x16, 0x54, 0x65, 0x73, 0x74,
	0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x50,
	0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x54, 0x65, 0x73, 0x74, 0x50, 0x65, 0x72, 0x73, 0x69,
	0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44,
	0x0a, 0x19, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x64,
	0x72, 0x79, 0x5f, 0x72, 0x75, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x72,
	0x79, 0x52, 0x75, 0x6e, 0x22, 0x1c, 0x0a, 0x1a, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50,
	0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x9c, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74,
	0x61, 0x73, 0x6b, 0x42, 0x0c, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x68, 0x6f, 0x6e, 0x6d, 0x61, 0x70, 0x6c, 0x65, 0x2f, 0x6d, 0x61, 0x70, 0x6c, 0x65, 0x2d, 0x66,
	0x69, 0x6c, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x61,
	0x73, 0x6b, 0xa2, 0x02, 0x03, 0x41, 0x54, 0x58, 0xaa, 0x02, 0x08, 0x41, 0x70, 0x69, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0xca, 0x02, 0x08, 0x41, 0x70, 0x69, 0x5c, 0x54, 0x61, 0x73, 0x6b, 0xe2, 0x02,
	0x14, 0x41, 0x70, 0x69, 0x5c, 0x54, 0x61, 0x73, 0x6b, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x41, 0x70, 0x69, 0x3a, 0x3a, 0x54, 0x61, 0x73,
	0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_task_persist_proto_rawDescOnce sync.Once
	file_api_task_persist_proto_rawDescData = file_api_task_persist_proto_rawDesc
)

func file_api_task_persist_proto_rawDescGZIP() []byte {
	file_api_task_persist_proto_rawDescOnce.Do(func() {
		file_api_task_persist_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_task_persist_proto_rawDescData)
	})
	return file_api_task_persist_proto_rawDescData
}

var file_api_task_persist_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_task_persist_proto_goTypes = []interface{}{
	(*PersistTask)(nil),                // 0: api.task.PersistTask
	(*ListPersistTasksRequest)(nil),    // 1: api.task.ListPersistTasksRequest
	(*ListPersistTasksResponse)(nil),   // 2: api.task.ListPersistTasksResponse
	(*CreatePersistTaskRequest)(nil),   // 3: api.task.CreatePersistTaskRequest
	(*CreatePersistTaskResponse)(nil),  // 4: api.task.CreatePersistTaskResponse
	(*UpdatePersistTaskRequest)(nil),   // 5: api.task.UpdatePersistTaskRequest
	(*UpdatePersistTaskResponse)(nil),  // 6: api.task.UpdatePersistTaskResponse
	(*DeletePersistTaskRequest)(nil),   // 7: api.task.DeletePersistTaskRequest
	(*DeletePersistTaskResponse)(nil),  // 8: api.task.DeletePersistTaskResponse
	(*TestPersistTaskRequest)(nil),     // 9: api.task.TestPersistTaskRequest
	(*TestPersistTaskResponse)(nil),    // 10: api.task.TestPersistTaskResponse
	(*ExecutePersistTaskRequest)(nil),  // 11: api.task.ExecutePersistTaskRequest
	(*ExecutePersistTaskResponse)(nil), // 12: api.task.ExecutePersistTaskResponse
	nil,                                // 13: api.task.ListPersistTasksRequest.FilterEntry
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
}
var file_api_task_persist_proto_depIdxs = []int32{
	14, // 0: api.task.PersistTask.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: api.task.PersistTask.updated_at:type_name -> google.protobuf.Timestamp
	13, // 2: api.task.ListPersistTasksRequest.filter:type_name -> api.task.ListPersistTasksRequest.FilterEntry
	0,  // 3: api.task.ListPersistTasksResponse.results:type_name -> api.task.PersistTask
	0,  // 4: api.task.CreatePersistTaskRequest.payload:type_name -> api.task.PersistTask
	0,  // 5: api.task.CreatePersistTaskResponse.result:type_name -> api.task.PersistTask
	0,  // 6: api.task.UpdatePersistTaskRequest.payload:type_name -> api.task.PersistTask
	0,  // 7: api.task.UpdatePersistTaskResponse.result:type_name -> api.task.PersistTask
	0,  // 8: api.task.TestPersistTaskRequest.payload:type_name -> api.task.PersistTask
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_task_persist_proto_init() }
func file_api_task_persist_proto_init() {
	if File_api_task_persist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_task_persist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersistTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPersistTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPersistTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePersistTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePersistTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePersistTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePersistTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePersistTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePersistTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestPersistTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestPersistTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutePersistTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_task_persist_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutePersistTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_task_persist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_task_persist_proto_goTypes,
		DependencyIndexes: file_api_task_persist_proto_depIdxs,
		MessageInfos:      file_api_task_persist_proto_msgTypes,
	}.Build()
	File_api_task_persist_proto = out.File
	file_api_task_persist_proto_rawDesc = nil
	file_api_task_persist_proto_goTypes = nil
	file_api_task_persist_proto_depIdxs = nil
}
