// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/task/service.proto

package task

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_task_service_proto protoreflect.FileDescriptor

const file_api_task_service_proto_rawDesc = "" +
	"\n" +
	"\x16api/task/service.proto\x12\bapi.task\x1a\x1cgoogle/api/annotations.proto\x1a\x13api/task/task.proto\x1a\x16api/task/persist.proto2\xde\b\n" +
	"\vTaskService\x12_\n" +
	"\tListTasks\x12\x1a.api.task.ListTasksRequest\x1a\x1b.api.task.ListTasksResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/task/list\x12`\n" +
	"\tRetryTask\x12\x1a.api.task.RetryTaskRequest\x1a\x1b.api.task.RetryTaskResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/task/retry\x12d\n" +
	"\n" +
	"CancelTask\x12\x1b.api.task.CancelTaskRequest\x1a\x1c.api.task.CancelTaskResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/task/cancel\x12d\n" +
	"\n" +
	"RemoveTask\x12\x1b.api.task.RemoveTaskRequest\x1a\x1c.api.task.RemoveTaskResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/task/remove\x12y\n" +
	"\x10ListPersistTasks\x12!.api.task.ListPersistTasksRequest\x1a\".api.task.ListPersistTasksResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/task/persist/list\x12z\n" +
	"\x11CreatePersistTask\x12\".api.task.CreatePersistTaskRequest\x1a#.api.task.CreatePersistTaskResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/task/persist\x12\x8d\x01\n" +
	"\x11UpdatePersistTask\x12\".api.task.UpdatePersistTaskRequest\x1a#.api.task.UpdatePersistTaskResponse\"/\x82\xd3\xe4\x93\x02):\apayload\x1a\x1e/api/task/persist/{payload.id}\x12|\n" +
	"\x11DeletePersistTask\x12\".api.task.DeletePersistTaskRequest\x1a#.api.task.DeletePersistTaskResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/task/persist/{id}\x12X\n" +
	"\x0fTestPersistTask\x12 .api.task.TestPersistTaskRequest\x1a!.api.task.TestPersistTaskResponse\"\x00\x12a\n" +
	"\x12ExecutePersistTask\x12#.api.task.ExecutePersistTaskRequest\x1a$.api.task.ExecutePersistTaskResponse\"\x00B\x9c\x01\n" +
	"\fcom.api.taskB\fServiceProtoP\x01Z=github.com/honmaple/maple-file/server/internal/proto/api/task\xa2\x02\x03ATX\xaa\x02\bApi.Task\xca\x02\bApi\\Task\xe2\x02\x14Api\\Task\\GPBMetadata\xea\x02\tApi::Taskb\x06proto3"

var file_api_task_service_proto_goTypes = []any{
	(*ListTasksRequest)(nil),           // 0: api.task.ListTasksRequest
	(*RetryTaskRequest)(nil),           // 1: api.task.RetryTaskRequest
	(*CancelTaskRequest)(nil),          // 2: api.task.CancelTaskRequest
	(*RemoveTaskRequest)(nil),          // 3: api.task.RemoveTaskRequest
	(*ListPersistTasksRequest)(nil),    // 4: api.task.ListPersistTasksRequest
	(*CreatePersistTaskRequest)(nil),   // 5: api.task.CreatePersistTaskRequest
	(*UpdatePersistTaskRequest)(nil),   // 6: api.task.UpdatePersistTaskRequest
	(*DeletePersistTaskRequest)(nil),   // 7: api.task.DeletePersistTaskRequest
	(*TestPersistTaskRequest)(nil),     // 8: api.task.TestPersistTaskRequest
	(*ExecutePersistTaskRequest)(nil),  // 9: api.task.ExecutePersistTaskRequest
	(*ListTasksResponse)(nil),          // 10: api.task.ListTasksResponse
	(*RetryTaskResponse)(nil),          // 11: api.task.RetryTaskResponse
	(*CancelTaskResponse)(nil),         // 12: api.task.CancelTaskResponse
	(*RemoveTaskResponse)(nil),         // 13: api.task.RemoveTaskResponse
	(*ListPersistTasksResponse)(nil),   // 14: api.task.ListPersistTasksResponse
	(*CreatePersistTaskResponse)(nil),  // 15: api.task.CreatePersistTaskResponse
	(*UpdatePersistTaskResponse)(nil),  // 16: api.task.UpdatePersistTaskResponse
	(*DeletePersistTaskResponse)(nil),  // 17: api.task.DeletePersistTaskResponse
	(*TestPersistTaskResponse)(nil),    // 18: api.task.TestPersistTaskResponse
	(*ExecutePersistTaskResponse)(nil), // 19: api.task.ExecutePersistTaskResponse
}
var file_api_task_service_proto_depIdxs = []int32{
	0,  // 0: api.task.TaskService.ListTasks:input_type -> api.task.ListTasksRequest
	1,  // 1: api.task.TaskService.RetryTask:input_type -> api.task.RetryTaskRequest
	2,  // 2: api.task.TaskService.CancelTask:input_type -> api.task.CancelTaskRequest
	3,  // 3: api.task.TaskService.RemoveTask:input_type -> api.task.RemoveTaskRequest
	4,  // 4: api.task.TaskService.ListPersistTasks:input_type -> api.task.ListPersistTasksRequest
	5,  // 5: api.task.TaskService.CreatePersistTask:input_type -> api.task.CreatePersistTaskRequest
	6,  // 6: api.task.TaskService.UpdatePersistTask:input_type -> api.task.UpdatePersistTaskRequest
	7,  // 7: api.task.TaskService.DeletePersistTask:input_type -> api.task.DeletePersistTaskRequest
	8,  // 8: api.task.TaskService.TestPersistTask:input_type -> api.task.TestPersistTaskRequest
	9,  // 9: api.task.TaskService.ExecutePersistTask:input_type -> api.task.ExecutePersistTaskRequest
	10, // 10: api.task.TaskService.ListTasks:output_type -> api.task.ListTasksResponse
	11, // 11: api.task.TaskService.RetryTask:output_type -> api.task.RetryTaskResponse
	12, // 12: api.task.TaskService.CancelTask:output_type -> api.task.CancelTaskResponse
	13, // 13: api.task.TaskService.RemoveTask:output_type -> api.task.RemoveTaskResponse
	14, // 14: api.task.TaskService.ListPersistTasks:output_type -> api.task.ListPersistTasksResponse
	15, // 15: api.task.TaskService.CreatePersistTask:output_type -> api.task.CreatePersistTaskResponse
	16, // 16: api.task.TaskService.UpdatePersistTask:output_type -> api.task.UpdatePersistTaskResponse
	17, // 17: api.task.TaskService.DeletePersistTask:output_type -> api.task.DeletePersistTaskResponse
	18, // 18: api.task.TaskService.TestPersistTask:output_type -> api.task.TestPersistTaskResponse
	19, // 19: api.task.TaskService.ExecutePersistTask:output_type -> api.task.ExecutePersistTaskResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_task_service_proto_init() }
func file_api_task_service_proto_init() {
	if File_api_task_service_proto != nil {
		return
	}
	file_api_task_task_proto_init()
	file_api_task_persist_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_task_service_proto_rawDesc), len(file_api_task_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_task_service_proto_goTypes,
		DependencyIndexes: file_api_task_service_proto_depIdxs,
	}.Build()
	File_api_task_service_proto = out.File
	file_api_task_service_proto_goTypes = nil
	file_api_task_service_proto_depIdxs = nil
}
