// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/task/task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 0
	TaskState_TASK_STATE_RUNNING     TaskState = 1
	TaskState_TASK_STATE_SUCCEEDED   TaskState = 2
	TaskState_TASK_STATE_CANCELING   TaskState = 3
	TaskState_TASK_STATE_CANCELED    TaskState = 4
	TaskState_TASK_STATE_FAILED      TaskState = 5
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		// Duplicate value: 0: "TASK_STATE_PENDING",
		1: "TASK_STATE_RUNNING",
		2: "TASK_STATE_SUCCEEDED",
		3: "TASK_STATE_CANCELING",
		4: "TASK_STATE_CANCELED",
		5: "TASK_STATE_FAILED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     0,
		"TASK_STATE_RUNNING":     1,
		"TASK_STATE_SUCCEEDED":   2,
		"TASK_STATE_CANCELING":   3,
		"TASK_STATE_CANCELED":    4,
		"TASK_STATE_FAILED":      5,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_task_task_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_api_task_task_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_api_task_task_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: gorm:"not null;unique"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" gorm:"not null;unique"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	EndTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"not null;"
	Name          string    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty" gorm:"not null;"`
	State         TaskState `protobuf:"varint,5,opt,name=state,proto3,enum=api.task.TaskState" json:"state,omitempty"`
	Progress      float64   `protobuf:"fixed64,6,opt,name=progress,proto3" json:"progress,omitempty"`
	ProgressState string    `protobuf:"bytes,7,opt,name=progress_state,json=progressState,proto3" json:"progress_state,omitempty"`
	Log           string    `protobuf:"bytes,8,opt,name=log,proto3" json:"log,omitempty"`
	Err           string    `protobuf:"bytes,9,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_task_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_task_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Task) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *Task) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Task) GetProgressState() string {
	if x != nil {
		return x.ProgressState
	}
	return ""
}

func (x *Task) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *Task) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        map[string]string      `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_task_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_task_task_proto_rawDescGZIP(), []int{1}
}

func (x *ListTasksRequest) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Task                `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_task_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_task_task_proto_rawDescGZIP(), []int{2}
}

func (x *ListTasksResponse) GetResults() []*Task {
	if x != nil {
		return x.Results
	}
	return nil
}

type RetryTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []string               `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskRequest) Reset() {
	*x = RetryTaskRequest{}
	mi := &file_api_task_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskRequest) ProtoMessage() {}

func (x *RetryTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskRequest.ProtoReflect.Descriptor instead.
func (*RetryTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_task_proto_rawDescGZIP(), []int{3}
}

func (x *RetryTaskRequest) GetTasks() []string {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type RetryTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskResponse) Reset() {
	*x = RetryTaskResponse{}
	mi := &file_api_task_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskResponse) ProtoMessage() {}

func (x *RetryTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskResponse.ProtoReflect.Descriptor instead.
func (*RetryTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_task_proto_rawDescGZIP(), []int{4}
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []string               `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_api_task_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_task_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTaskRequest) GetTasks() []string {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_api_task_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_task_proto_rawDescGZIP(), []int{6}
}

type RemoveTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []string               `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTaskRequest) Reset() {
	*x = RemoveTaskRequest{}
	mi := &file_api_task_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTaskRequest) ProtoMessage() {}

func (x *RemoveTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTaskRequest.ProtoReflect.Descriptor instead.
func (*RemoveTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_task_task_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveTaskRequest) GetTasks() []string {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type RemoveTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTaskResponse) Reset() {
	*x = RemoveTaskResponse{}
	mi := &file_api_task_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTaskResponse) ProtoMessage() {}

func (x *RemoveTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTaskResponse.ProtoReflect.Descriptor instead.
func (*RemoveTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_task_proto_rawDescGZIP(), []int{8}
}

var File_api_task_task_proto protoreflect.FileDescriptor

const file_api_task_task_proto_rawDesc = "" +
	"\n" +
	"\x13api/task/task.proto\x12\bapi.task\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12)\n" +
	"\x05state\x18\x05 \x01(\x0e2\x13.api.task.TaskStateR\x05state\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x01R\bprogress\x12%\n" +
	"\x0eprogress_state\x18\a \x01(\tR\rprogressState\x12\x10\n" +
	"\x03log\x18\b \x01(\tR\x03log\x12\x10\n" +
	"\x03err\x18\t \x01(\tR\x03err\"\x8d\x01\n" +
	"\x10ListTasksRequest\x12>\n" +
	"\x06filter\x18\x01 \x03(\v2&.api.task.ListTasksRequest.FilterEntryR\x06filter\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x11ListTasksResponse\x12(\n" +
	"\aresults\x18\x01 \x03(\v2\x0e.api.task.TaskR\aresults\"(\n" +
	"\x10RetryTaskRequest\x12\x14\n" +
	"\x05tasks\x18\x01 \x03(\tR\x05tasks\"\x13\n" +
	"\x11RetryTaskResponse\")\n" +
	"\x11CancelTaskRequest\x12\x14\n" +
	"\x05tasks\x18\x01 \x03(\tR\x05tasks\"\x14\n" +
	"\x12CancelTaskResponse\")\n" +
	"\x11RemoveTaskRequest\x12\x14\n" +
	"\x05tasks\x18\x01 \x03(\tR\x05tasks\"\x14\n" +
	"\x12RemoveTaskResponse*\xbf\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x01\x12\x18\n" +
	"\x14TASK_STATE_SUCCEEDED\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_CANCELING\x10\x03\x12\x17\n" +
	"\x13TASK_STATE_CANCELED\x10\x04\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x05\x1a\x02\x10\x01B\x99\x01\n" +
	"\fcom.api.taskB\tTaskProtoP\x01Z=github.com/honmaple/maple-file/server/internal/proto/api/task\xa2\x02\x03ATX\xaa\x02\bApi.Task\xca\x02\bApi\\Task\xe2\x02\x14Api\\Task\\GPBMetadata\xea\x02\tApi::Taskb\x06proto3"

var (
	file_api_task_task_proto_rawDescOnce sync.Once
	file_api_task_task_proto_rawDescData []byte
)

func file_api_task_task_proto_rawDescGZIP() []byte {
	file_api_task_task_proto_rawDescOnce.Do(func() {
		file_api_task_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_task_task_proto_rawDesc), len(file_api_task_task_proto_rawDesc)))
	})
	return file_api_task_task_proto_rawDescData
}

var file_api_task_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_task_task_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_task_task_proto_goTypes = []any{
	(TaskState)(0),                // 0: api.task.TaskState
	(*Task)(nil),                  // 1: api.task.Task
	(*ListTasksRequest)(nil),      // 2: api.task.ListTasksRequest
	(*ListTasksResponse)(nil),     // 3: api.task.ListTasksResponse
	(*RetryTaskRequest)(nil),      // 4: api.task.RetryTaskRequest
	(*RetryTaskResponse)(nil),     // 5: api.task.RetryTaskResponse
	(*CancelTaskRequest)(nil),     // 6: api.task.CancelTaskRequest
	(*CancelTaskResponse)(nil),    // 7: api.task.CancelTaskResponse
	(*RemoveTaskRequest)(nil),     // 8: api.task.RemoveTaskRequest
	(*RemoveTaskResponse)(nil),    // 9: api.task.RemoveTaskResponse
	nil,                           // 10: api.task.ListTasksRequest.FilterEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_api_task_task_proto_depIdxs = []int32{
	11, // 0: api.task.Task.start_time:type_name -> google.protobuf.Timestamp
	11, // 1: api.task.Task.end_time:type_name -> google.protobuf.Timestamp
	0,  // 2: api.task.Task.state:type_name -> api.task.TaskState
	10, // 3: api.task.ListTasksRequest.filter:type_name -> api.task.ListTasksRequest.FilterEntry
	1,  // 4: api.task.ListTasksResponse.results:type_name -> api.task.Task
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_task_task_proto_init() }
func file_api_task_task_proto_init() {
	if File_api_task_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_task_task_proto_rawDesc), len(file_api_task_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_task_task_proto_goTypes,
		DependencyIndexes: file_api_task_task_proto_depIdxs,
		EnumInfos:         file_api_task_task_proto_enumTypes,
		MessageInfos:      file_api_task_task_proto_msgTypes,
	}.Build()
	File_api_task_task_proto = out.File
	file_api_task_task_proto_goTypes = nil
	file_api_task_task_proto_depIdxs = nil
}
