// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/setting/info.proto

package setting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Runtime       string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_api_setting_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_api_setting_info_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Info) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Info) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Info) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Info) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_api_setting_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_api_setting_info_proto_rawDescGZIP(), []int{1}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Info                  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_api_setting_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_api_setting_info_proto_rawDescGZIP(), []int{2}
}

func (x *InfoResponse) GetResult() *Info {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_setting_info_proto protoreflect.FileDescriptor

const file_api_setting_info_proto_rawDesc = "" +
	"\n" +
	"\x16api/setting/info.proto\x12\vapi.setting\"\x80\x01\n" +
	"\x04Info\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\r\n" +
	"\vInfoRequest\"9\n" +
	"\fInfoResponse\x12)\n" +
	"\x06result\x18\x01 \x01(\v2\x11.api.setting.InfoR\x06resultB\xab\x01\n" +
	"\x0fcom.api.settingB\tInfoProtoP\x01Z@github.com/honmaple/maple-file/server/internal/proto/api/setting\xa2\x02\x03ASX\xaa\x02\vApi.Setting\xca\x02\vApi\\Setting\xe2\x02\x17Api\\Setting\\GPBMetadata\xea\x02\fApi::Settingb\x06proto3"

var (
	file_api_setting_info_proto_rawDescOnce sync.Once
	file_api_setting_info_proto_rawDescData []byte
)

func file_api_setting_info_proto_rawDescGZIP() []byte {
	file_api_setting_info_proto_rawDescOnce.Do(func() {
		file_api_setting_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_setting_info_proto_rawDesc), len(file_api_setting_info_proto_rawDesc)))
	})
	return file_api_setting_info_proto_rawDescData
}

var file_api_setting_info_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_setting_info_proto_goTypes = []any{
	(*Info)(nil),         // 0: api.setting.Info
	(*InfoRequest)(nil),  // 1: api.setting.InfoRequest
	(*InfoResponse)(nil), // 2: api.setting.InfoResponse
}
var file_api_setting_info_proto_depIdxs = []int32{
	0, // 0: api.setting.InfoResponse.result:type_name -> api.setting.Info
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_setting_info_proto_init() }
func file_api_setting_info_proto_init() {
	if File_api_setting_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_setting_info_proto_rawDesc), len(file_api_setting_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_setting_info_proto_goTypes,
		DependencyIndexes: file_api_setting_info_proto_depIdxs,
		MessageInfos:      file_api_setting_info_proto_msgTypes,
	}.Build()
	File_api_setting_info_proto = out.File
	file_api_setting_info_proto_goTypes = nil
	file_api_setting_info_proto_depIdxs = nil
}
