// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/setting/service.proto

package setting

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_setting_service_proto protoreflect.FileDescriptor

const file_api_setting_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/setting/service.proto\x12\vapi.setting\x1a\x1cgoogle/api/annotations.proto\x1a\x16api/setting/info.proto\x1a\x19api/setting/setting.proto2\xae\x03\n" +
	"\rSystemService\x12N\n" +
	"\x04Info\x12\x18.api.setting.InfoRequest\x1a\x19.api.setting.InfoResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/info\x12p\n" +
	"\fResetSetting\x12 .api.setting.ResetSettingRequest\x1a!.api.setting.ResetSettingResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x13/api/settings/reset\x12p\n" +
	"\rUpdateSetting\x12!.api.setting.UpdateSettingRequest\x1a\".api.setting.UpdateSettingResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/settings\x12i\n" +
	"\n" +
	"GetSetting\x12\x1e.api.setting.GetSettingRequest\x1a\x1f.api.setting.GetSettingResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/setting/{key}B\xae\x01\n" +
	"\x0fcom.api.settingB\fServiceProtoP\x01Z@github.com/honmaple/maple-file/server/internal/proto/api/setting\xa2\x02\x03ASX\xaa\x02\vApi.Setting\xca\x02\vApi\\Setting\xe2\x02\x17Api\\Setting\\GPBMetadata\xea\x02\fApi::Settingb\x06proto3"

var file_api_setting_service_proto_goTypes = []any{
	(*InfoRequest)(nil),           // 0: api.setting.InfoRequest
	(*ResetSettingRequest)(nil),   // 1: api.setting.ResetSettingRequest
	(*UpdateSettingRequest)(nil),  // 2: api.setting.UpdateSettingRequest
	(*GetSettingRequest)(nil),     // 3: api.setting.GetSettingRequest
	(*InfoResponse)(nil),          // 4: api.setting.InfoResponse
	(*ResetSettingResponse)(nil),  // 5: api.setting.ResetSettingResponse
	(*UpdateSettingResponse)(nil), // 6: api.setting.UpdateSettingResponse
	(*GetSettingResponse)(nil),    // 7: api.setting.GetSettingResponse
}
var file_api_setting_service_proto_depIdxs = []int32{
	0, // 0: api.setting.SystemService.Info:input_type -> api.setting.InfoRequest
	1, // 1: api.setting.SystemService.ResetSetting:input_type -> api.setting.ResetSettingRequest
	2, // 2: api.setting.SystemService.UpdateSetting:input_type -> api.setting.UpdateSettingRequest
	3, // 3: api.setting.SystemService.GetSetting:input_type -> api.setting.GetSettingRequest
	4, // 4: api.setting.SystemService.Info:output_type -> api.setting.InfoResponse
	5, // 5: api.setting.SystemService.ResetSetting:output_type -> api.setting.ResetSettingResponse
	6, // 6: api.setting.SystemService.UpdateSetting:output_type -> api.setting.UpdateSettingResponse
	7, // 7: api.setting.SystemService.GetSetting:output_type -> api.setting.GetSettingResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_setting_service_proto_init() }
func file_api_setting_service_proto_init() {
	if File_api_setting_service_proto != nil {
		return
	}
	file_api_setting_info_proto_init()
	file_api_setting_setting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_setting_service_proto_rawDesc), len(file_api_setting_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_setting_service_proto_goTypes,
		DependencyIndexes: file_api_setting_service_proto_depIdxs,
	}.Build()
	File_api_setting_service_proto = out.File
	file_api_setting_service_proto_goTypes = nil
	file_api_setting_service_proto_depIdxs = nil
}
