// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/setting/setting.proto

package setting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Setting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: gorm:"primary_key;auto_increment"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key;auto_increment"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"size:128;not null;unique"
	Key           string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty" gorm:"size:128;not null;unique"`
	Value         string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting) Reset() {
	*x = Setting{}
	mi := &file_api_setting_setting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting) ProtoMessage() {}

func (x *Setting) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_setting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting.ProtoReflect.Descriptor instead.
func (*Setting) Descriptor() ([]byte, []int) {
	return file_api_setting_setting_proto_rawDescGZIP(), []int{0}
}

func (x *Setting) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Setting) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Setting) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Setting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Setting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingRequest) Reset() {
	*x = GetSettingRequest{}
	mi := &file_api_setting_setting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingRequest) ProtoMessage() {}

func (x *GetSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_setting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingRequest.ProtoReflect.Descriptor instead.
func (*GetSettingRequest) Descriptor() ([]byte, []int) {
	return file_api_setting_setting_proto_rawDescGZIP(), []int{1}
}

func (x *GetSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Setting               `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingResponse) Reset() {
	*x = GetSettingResponse{}
	mi := &file_api_setting_setting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingResponse) ProtoMessage() {}

func (x *GetSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_setting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingResponse.ProtoReflect.Descriptor instead.
func (*GetSettingResponse) Descriptor() ([]byte, []int) {
	return file_api_setting_setting_proto_rawDescGZIP(), []int{2}
}

func (x *GetSettingResponse) GetResult() *Setting {
	if x != nil {
		return x.Result
	}
	return nil
}

type UpdateSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingRequest) Reset() {
	*x = UpdateSettingRequest{}
	mi := &file_api_setting_setting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingRequest) ProtoMessage() {}

func (x *UpdateSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_setting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingRequest) Descriptor() ([]byte, []int) {
	return file_api_setting_setting_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateSettingRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Setting               `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingResponse) Reset() {
	*x = UpdateSettingResponse{}
	mi := &file_api_setting_setting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingResponse) ProtoMessage() {}

func (x *UpdateSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_setting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingResponse.ProtoReflect.Descriptor instead.
func (*UpdateSettingResponse) Descriptor() ([]byte, []int) {
	return file_api_setting_setting_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSettingResponse) GetResult() *Setting {
	if x != nil {
		return x.Result
	}
	return nil
}

type ResetSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetSettingRequest) Reset() {
	*x = ResetSettingRequest{}
	mi := &file_api_setting_setting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSettingRequest) ProtoMessage() {}

func (x *ResetSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_setting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetSettingRequest.ProtoReflect.Descriptor instead.
func (*ResetSettingRequest) Descriptor() ([]byte, []int) {
	return file_api_setting_setting_proto_rawDescGZIP(), []int{5}
}

func (x *ResetSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ResetSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetSettingResponse) Reset() {
	*x = ResetSettingResponse{}
	mi := &file_api_setting_setting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSettingResponse) ProtoMessage() {}

func (x *ResetSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_setting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetSettingResponse.ProtoReflect.Descriptor instead.
func (*ResetSettingResponse) Descriptor() ([]byte, []int) {
	return file_api_setting_setting_proto_rawDescGZIP(), []int{6}
}

var File_api_setting_setting_proto protoreflect.FileDescriptor

const file_api_setting_setting_proto_rawDesc = "" +
	"\n" +
	"\x19api/setting/setting.proto\x12\vapi.setting\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x01\n" +
	"\aSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\"%\n" +
	"\x11GetSettingRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"B\n" +
	"\x12GetSettingResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.api.setting.SettingR\x06result\">\n" +
	"\x14UpdateSettingRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"E\n" +
	"\x15UpdateSettingResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.api.setting.SettingR\x06result\"'\n" +
	"\x13ResetSettingRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x16\n" +
	"\x14ResetSettingResponseB\xae\x01\n" +
	"\x0fcom.api.settingB\fSettingProtoP\x01Z@github.com/honmaple/maple-file/server/internal/proto/api/setting\xa2\x02\x03ASX\xaa\x02\vApi.Setting\xca\x02\vApi\\Setting\xe2\x02\x17Api\\Setting\\GPBMetadata\xea\x02\fApi::Settingb\x06proto3"

var (
	file_api_setting_setting_proto_rawDescOnce sync.Once
	file_api_setting_setting_proto_rawDescData []byte
)

func file_api_setting_setting_proto_rawDescGZIP() []byte {
	file_api_setting_setting_proto_rawDescOnce.Do(func() {
		file_api_setting_setting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_setting_setting_proto_rawDesc), len(file_api_setting_setting_proto_rawDesc)))
	})
	return file_api_setting_setting_proto_rawDescData
}

var file_api_setting_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_setting_setting_proto_goTypes = []any{
	(*Setting)(nil),               // 0: api.setting.Setting
	(*GetSettingRequest)(nil),     // 1: api.setting.GetSettingRequest
	(*GetSettingResponse)(nil),    // 2: api.setting.GetSettingResponse
	(*UpdateSettingRequest)(nil),  // 3: api.setting.UpdateSettingRequest
	(*UpdateSettingResponse)(nil), // 4: api.setting.UpdateSettingResponse
	(*ResetSettingRequest)(nil),   // 5: api.setting.ResetSettingRequest
	(*ResetSettingResponse)(nil),  // 6: api.setting.ResetSettingResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_api_setting_setting_proto_depIdxs = []int32{
	7, // 0: api.setting.Setting.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: api.setting.Setting.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: api.setting.GetSettingResponse.result:type_name -> api.setting.Setting
	0, // 3: api.setting.UpdateSettingResponse.result:type_name -> api.setting.Setting
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_setting_setting_proto_init() }
func file_api_setting_setting_proto_init() {
	if File_api_setting_setting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_setting_setting_proto_rawDesc), len(file_api_setting_setting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_setting_setting_proto_goTypes,
		DependencyIndexes: file_api_setting_setting_proto_depIdxs,
		MessageInfos:      file_api_setting_setting_proto_msgTypes,
	}.Build()
	File_api_setting_setting_proto = out.File
	file_api_setting_setting_proto_goTypes = nil
	file_api_setting_setting_proto_depIdxs = nil
}
